### ISSUE TITLE
When will be the code released for Active Adversarial Domain Adaptation?

### ISSUE THREAD

**Issue by lomun123** [jongchyisu/mvcnn_pytorch#11]
When will be the code released for Active Adversarial Domain Adaptation?

**Comment by jongchyisu** [comment]
Hi, currently I don't have the schedule for releasing the code. First, there is a company policy since it's an internship work. Second, we are using the typical training settings as prior works (DANN and Faster-RCNN), as for the active learning part you can calculate the discriminator scores for all unlabeled target data and sort them. Last, this paper has not been accepted yet except for a workshop with extended abstract format. Let me know if you have issue reproducing the results.
